export const AUTH_PROGRESS = 'AUTH_PROGRESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_REGISTER_PROGRESS = 'USER_REGISTER_PROGRESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const USER_INFO_PROGRESS = 'USER_INFO_PROGRESS';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const RESET_LECTURES = 'RESET_LECTURES';
export const LECTURES_PROGRESS = 'LECTURES_PROGRESS';
export const LECTURES_SUCCESS = 'LECTURES_SUCCESS';
export const LECTURES_FAIL = 'LECTURES_FAIL';

export const RESET_ATTENDENCE = 'RESET_ATTENDENCE';
export const ATTENDENCE_PROGRESS = 'ATTENDENCE_PROGRESS';
export const ATTENDENCE_SUCCESS = 'ATTENDENCE_SUCCESS';
export const ATTENDENCE_FAIL = 'ATTENDENCE_FAIL';

export const RESET_LECTURE_STUDENTS = 'RESET_LECTURE_STUDENTS';
export const LECTURE_STUDENTS_PROGRESS = 'LECTURE_STUDENTS_PROGRESS';
export const LECTURE_STUDENTS_SUCCESS = 'LECTURE_STUDENTS_SUCCESS';
export const LECTURE_STUDENTS_FAIL = 'LECTURE_STUDENTS_FAIL';

export const RESET_USER_ATTENDENCE = 'RESET_USER_ATTENDENCE';
export const USER_ATTENDENCE_PROGRESS = 'USER_ATTENDENCE_PROGRESS';
export const USER_ATTENDENCE_SUCCESS = 'USER_ATTENDENCE_SUCCESS';
export const USER_ATTENDENCE_FAIL = 'USER_ATTENDENCE_FAIL';

export const ALL_LECTURES_PROGRESS = 'ALL_LECTURES_PROGRESS';
export const ALL_LECTURES_SUCCESS = 'ALL_LECTURES_SUCCESS';
export const ALL_LECTURES_FAIL = 'ALL_LECTURES_FAIL';

export const SELECT_LECTURES_PROGRESS = 'SELECT_LECTURES_PROGRESS';
export const SELECT_LECTURES_FAIL = 'SELECT_LECTURES_FAIL';
export const SELECT_LECTURES_SUCCESS = 'SELECT_LECTURES_SUCCESS';

export const SET_IS_SELECTED_LECTURES = 'SET_IS_SELECTED_LECTURES';
