export const AUTH_PROGRESS = 'AUTH_PROGRESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_REGISTER_PROGRESS = 'USER_REGISTER_PROGRESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_INFO_COMPLETE = 'USER_INFO_COMPLETE';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const RESET_LECTURES = 'RESET_LECTURES';
export const LECTURES_PROGRESS = 'LECTURES_PROGRESS';
export const LECTURES_SUCCESS = 'LECTURES_SUCCESS';
export const LECTURES_FAIL = 'LECTURES_FAIL';

export const RESET_ATTENDENCE = 'RESET_ATTENDENCE';
export const ATTENDENCE_PROGRESS = 'ATTENDENCE_PROGRESS';
export const ATTENDENCE_SUCCESS = 'ATTENDENCE_SUCCESS';
export const ATTENDENCE_FAIL = 'ATTENDENCE_FAIL';
